"""The heartbeat instruction is generated by vibe and copied verbatim.

Observed on socialmore (2026-10-03, vibe 5.0.1 on Codex): the first shift
wrote its own heartbeat prompt.  Every beat ran a full `vibe resume` plus a
mailbox scan instead of the preflight, never registered an address, never
rotated -- context climbed from 63k to 214k and an idle beat cost 5-15x the
design.  Telling the agent "make the preflight the first step" left the
wording to the agent; these tests pin a single vibe-owned text instead, and
make `resume` (what a drifting heartbeat actually calls) keep asking for the
start-of-shift duties until the shift registers.
"""
import unittest

from vibe_guide.cli import run_cli
from vibe_guide.paths import ProjectPaths
from vibe_guide.protocols import load_protocol
from vibe_guide.supervisor import heartbeat_prompt, register_supervisor_address

from tests.support_v45_authorize import publish_complex_probe


class HeartbeatPromptShapeTests(unittest.TestCase):
    def test_first_step_is_only_the_preflight(self):
        text = heartbeat_prompt("plan-a", "run-b")
        first = text.index("vibe supervisor-preflight --run-id run-b")
        self.assertLess(first, text.index("vibe resume"))
        self.assertIn("--session-record <本会话记录路径>", text)

    def test_every_preflight_state_has_a_branch(self):
        text = heartbeat_prompt("plan-a", "run-b")
        for state in ("idle", "work", "unknown", "rotate"):
            self.assertIn(state, text)

    def test_work_branch_serves_this_run(self):
        self.assertIn(
            "vibe resume --plan plan-a --run-id run-b",
            heartbeat_prompt("plan-a", "run-b"),
        )

    def test_prompt_forbids_rewriting(self):
        self.assertIn("逐字", heartbeat_prompt("plan-a", "run-b"))


class ProtocolCarriesTheSameTextTests(unittest.TestCase):
    def section(self, heading, next_heading):
        text = load_protocol("prd-guide")
        start = text.index(heading)
        return text[start:text.index(next_heading, start)]

    def test_opening_step_embeds_the_generated_prompt_verbatim(self):
        opening = self.section("### 6.0", "### 6.1")
        self.assertIn(heartbeat_prompt("<plan_id>", "<run-id>"), opening)

    def test_rotate_branch_reuses_the_same_prompt(self):
        discipline = self.section("### 6.5", "## 7. ")
        rotate = [line for line in discipline.splitlines() if line.startswith("- 输出 `rotate`")]
        self.assertEqual(len(rotate), 1)
        self.assertIn("同一段心跳指令", rotate[0])


class EntryProtocolPointsAtTheGeneratedPromptTests(unittest.TestCase):
    """Review P2: the entry protocol is read first; it must not invite a self-written heartbeat."""

    def test_first_shift_line_requires_the_generated_prompt(self):
        text = load_protocol("vibe-entry")
        path = text[text.index("## 3."):text.index("## 4.")]
        lines = [line for line in path.splitlines() if "首班监工开工两件事" in line]
        self.assertEqual(len(lines), 1)
        self.assertIn("逐字使用 vibe 生成的那一段", lines[0])
        self.assertIn("不得自己另写", lines[0])


class CliPrintsThePromptTests(unittest.TestCase):
    def start(self):
        root = publish_complex_probe(self)
        run_cli(["authorize", "--json", "--plan", "probe-plan", "--authorize", "AUTHORIZE"], root)
        started = run_cli(["monitor", "--json", "--plan", "probe-plan", "--authorize", "AUTHORIZE"], root)
        return root, started.payload["run_id"], started

    def test_monitor_handoff_carries_the_filled_prompt(self):
        _root, run_id, started = self.start()
        self.assertIn(heartbeat_prompt("probe-plan", run_id), started.payload["handoff"])

    def test_resume_keeps_asking_until_registered(self):
        root, run_id, _started = self.start()
        resumed = run_cli(["resume", "--plan", "probe-plan", "--run-id", run_id], root)
        self.assertIsNotNone(resumed.payload.get("run_id"), resumed.text)
        self.assertIn("vibe supervisor-register", resumed.text)
        self.assertIn(heartbeat_prompt("probe-plan", run_id), resumed.text)

        register_supervisor_address(
            ProjectPaths(root), run_id,
            {"provider": "codex", "session_id": "s-1", "host": "mac"},
        )
        again = run_cli(["resume", "--plan", "probe-plan", "--run-id", run_id], root)
        self.assertIsNotNone(again.payload.get("run_id"), again.text)
        self.assertNotIn("vibe supervisor-register", again.text)
        self.assertNotIn("handoff", again.payload)

    def test_status_stays_quiet(self):
        root, run_id, _started = self.start()
        shown = run_cli(["status", "--plan", "probe-plan", "--run-id", run_id], root)
        self.assertNotIn("vibe supervisor-register", shown.text)


if __name__ == "__main__":
    unittest.main()
